# Generated by Django 2.0 on 2018-01-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('receiver',),
            },
        ),
        migrations.CreateModel(
            name='GoogleForm',
            fields=[
                ('form_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('response_url', models.URLField(null=True)),
                ('form_type', models.CharField(choices=[('F', 'Full'), ('B', 'Basic')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('script_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('receiver',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_response_url', models.URLField()),
                ('activated', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('fun_to_work_with', models.PositiveSmallIntegerField()),
                ('gets_stuff_done', models.PositiveSmallIntegerField()),
                ('work_with', models.CharField(max_length=200)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.GoogleForm')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('unique_first_name', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('active_full_form', models.URLField(blank=True, null=True)),
                ('active_basic_form', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='responseset',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='responseset',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='googleform',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.User'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='active_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.ResponseSet'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_giver', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_receiver', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.ResponseSet'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackrequest',
            unique_together={('receiver', 'giver', 'requested_by')},
        ),
    ]
