# Generated by Django 2.0 on 2018-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180114_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_client_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleform',
            name='form_type',
            field=models.CharField(choices=[('F', 'Full'), ('B', 'Basic'), ('C', 'Client')], max_length=1),
        ),
    ]
