# Generated by Django 2.0 on 2018-01-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180106_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackUser',
        ),
        migrations.RemoveField(
            model_name='slackchat',
            name='members',
        ),
        migrations.AddField(
            model_name='responseset',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responseset',
            name='respondent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='feedback.User'),
        ),
        migrations.DeleteModel(
            name='SlackChat',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='requestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='feedback.User'),
        ),
        migrations.AddField(
            model_name='responseset',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='feedback.User'),
        ),
    ]
