# Generated by Django 2.0 on 2018-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180127_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_feedback_form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
