# Generated by Django 2.0 on 2018-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180106_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleform',
            name='response_url',
            field=models.URLField(null=True),
        ),
    ]
