# Generated by Django 2.0 on 2018-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_googleform_response_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
