# Generated by Django 2.0 on 2018-01-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_user_unique_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleform',
            name='script_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
