# Generated by Django 2.0 on 2018-01-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_googleform_script_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackrequest',
            options={'ordering': ('requester',)},
        ),
        migrations.AlterModelOptions(
            name='googleform',
            options={'ordering': ('receiver',)},
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='feedback.User'),
        ),
    ]
