# Generated by Django 2.0 on 2018-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20180114_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_basic_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active_full_form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
